# Generated by Django 3.0.6 on 2020-07-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fityfeed', '0002_auto_20200725_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='quantity',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
